### ISSUE TITLE
6. Request from vendor to see screenshot or mockup of what a vendor profile will look like (will help this person design their profile). (Cali)

### ISSUE THREAD

**Issue by uniphil** [uniphil/hes-vendor-dash-issues#12]
They’ll get a few days of this prior to the event

**Comment by SuperSparkplug** [comment]
https://grindspark.com/wp-content/gallery/canzine2020/Screen-Shot-2020-10-30-at-1.55.08-AM.png

**Comment by uniphil** [comment]
damn Jordan that screenshot is really nice!

Is it ok if I close this issue? Or would you like me to include that somewhere on the form as an example of what the final profile will look like?

**Comment by SuperSparkplug** [comment]
Might be good to include as an example... Also, it's a friend so it promotes them slightly lol.

**Comment by uniphil** [comment]
Great! and nice! :)

I need to know where it should go on the site / how it should be displayed. Drawing on a screenshot or something would be amazing ✨
