### ISSUE TITLE
Improve UI guidance around number of submitable items

### ISSUE THREAD

**Issue by uniphil** [uniphil/hes-vendor-dash-issues#13]
> Will all vendors have the option to upload 10 items, or is this just a demo? I ask because most TCAF exhibitor have a limit of 5 items, with the option to purchase more. How will we be able to add the specific number of items?
[Cali note]

follow up with help text?

**Comment by SuperSparkplug** [comment]
TCAF pushed for up to 9 or 10. Brendan did note difficulty with this but seemed to have found a workaround of some kind. If possible, I'd like us to push to 9. If 10 is too difficult, then cut it. Let me know how this goes.

**Comment by uniphil** [comment]
yep! Brendan did the fix already, 10 should be working. Remaining issue (low priority) is about vendor-facing documentation.

> most TCAF exhibitor have a limit of 5 items, with the option to purchase more.

I think in the meeting there was a suggestion to just add a help text detailing whatever the pricing policy is.

**Comment by uniphil** [comment]
See #47 for the Canzine-specific handling.

For TCAF, the way it was set up, is that each vendor can upload **5 items by default**. Increasing it to 10 requires an edit on the admin site.

If we want different behaviour (eg., 10 by default? give vendors a button to click to increase it?), I just need to know what we want.
