### ISSUE TITLE
Many users passwords got reset to blank

### ISSUE THREAD

**Issue by uniphil** [uniphil/hes-vendor-dash-issues#31]
The bug is fixed, but we'll need a way to handle affected accounts when it comes back online.

**Comment by SuperSparkplug** [comment]
Do we have a list of affected accounts?

**Comment by uniphil** [comment]
fixed via https://github.com/uniphil/festival-vendors/commit/915f899720cbd04df0ff7b9076de2e77566a3591

for affected accounts, the flow looks like this:


https://user-images.githubusercontent.com/205128/115185337-a1d7e880-a0ad-11eb-99d2-504b447edffb.mov
