### ISSUE TITLE
PDF uploads lose their original file names

### ISSUE THREAD

**Issue by uniphil** [uniphil/hes-vendor-dash-issues#37]
I know that this is probably working as intended, and might just cause more headaches with twine and shopify down the line, but it might come as a surprise to vendors that their `My Fair Blade-y.pdf` upload gets renamed to `1.pdf` when they click to download it.

Additionally, since we immediately forget the original filename, we can't show it in the user interface to remind them which PDF they uploaded as `PDF item 3` vs. `PDF item 4`.

🤷🏼‍♀️ low priority, but it could be a nice touch to keep the original name around.

**Comment by SuperSparkplug** [comment]
For PDFs, it's fine to keep the original file name. The file renaming is more of a thing for images specifically.

**Comment by uniphil** [comment]
gotcha.

I've left the actual file names alone for now, but updated the link storage to save the name. This way the original filename is shown when vendors are reviewing their uploads, and we have everything we need to either keep or drop the filename for shopify purposes later.
