### ISSUE TITLE
If I use Physical and Digital it gives me issues if I try to put grams and physical properties

### ISSUE THREAD

**Issue by uniphil** [uniphil/hes-vendor-dash-issues#8]
[Jordan notes]
[might be fixed? jordan to folllow up.]

**Comment by SuperSparkplug** [comment]
I think Brendan fixed this, but I'm unsure since the form is now down. I think "Physical and Digital" was changed to Choose format or something instead.

**Comment by uniphil** [comment]
Awesome! yeah, part made sense to me while I was working on the pricing always warning about being zero.

Staging is back up (see email) if you want to verify that this is fixed and we can close it out!

**Comment by uniphil** [comment]
closing as assumed fixed
